### ISSUE TITLE
The User->isAdmin function is not working in Moodle

### ISSUE THREAD

**Issue by jeffmiko** [celtic-project/LTI-PHP#10]
The isAdmin method of the User class is returning false for administrators. In Moodle 3.7 there are 3 roles being passed for my administrator account:
- http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator,
- http://purl.imsglobal.org/vocab/lis/v2/system/person#Administrator",
- http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor,

I am using Moodle 3.7 and LTI-PHP 4.0.1

**Comment by spvickers** [comment]
Which version of LTI are you using for your LTI launch messages?

**Comment by jeffmiko** [comment]
LTI 1.3

**Comment by spvickers** [comment]
The isAdmin method (and also the isLearner and isStaff methods) currently only checks the context-level roles and since Moodle is not sending context-level Administrator role, the method returns false.  I'll consider how best to handle system and institution level roles.  Thanks for reporting this.

**Comment by spvickers** [comment]
My apologies, on closer inspection you are quite right.  The code is trying to check the higher levels for Admin roles but failing to properly parse the new format.  I will submit a fix for this.
