### ISSUE TITLE
Blackboard send the launch_presentation_document_target in all-caps and causes an error

### ISSUE THREAD

**Issue by alexvanniel** [celtic-project/LTI-PHP#13]
When Blackboard launches the LTI tool in a new window for instance, the value it passes to the Tool is WINDOW and since this is not the same as window (which is on the allowed list and WINDOW isn't) the LTI Library thinks an invalid value was supplied and reports an error.
Casting the launch_presentation_document_target to a lowercase and optionally casting the accept_presentation_document_targets to lowercase could prevent further problems.
I have made PR for this. I am not sure if this needs some deeper adjustments on a further level down in the Tool.

**Comment by spvickers** [comment]
I would regard this as a bug in Blackboard, although the spec does not state that its list of examples is exhaustive or case sensitive, so perhaps this check is not valid and should be removed.  I'll investigate it, thanks.

**Comment by alexvanniel** [comment]
Thanks. It currently prevents the Blackboard administrator from having placements launch in a seperate window.
You could also cast the launch_presentation_document_target somewhere else to lower case. I have been trying to see if there is a better and proper location to do this in the library but failed, unfortunately :(

**Comment by spvickers** [comment]
Your workaround for now is just to comment out this test.

**Comment by spvickers** [comment]
The LTI 1.3 spec states that the value of the document_target claim "MUST be one of: frame, iframe, or window".  It does not indicate that this is case insensitive, and these values have been used in lowercase in earlier versions of the spec as well.  I would expect the accept_presentation_document_targets claim in a deep linking request to use the same values.  Hence I believe this is a bug in Blackboard which you should report to them.

**Comment by alexvanniel** [comment]
I will notify them and see what an dif they are planning to do something
about it. For a company that says to be actively part of the Lti standard,
this is a rather weird bug to have.

Op do 17 sep. 2020 11:35 schreef Stephen Vickers <notifications@github.com>:

**Comment by spvickers** [comment]
I have also asked IMS for clarification on the case sensitivity of this parameter.

**Comment by alexvanniel** [comment]
I have been in contact with one of the developers at Blackboard and he says it is indeed a bug. A issue will be created for it and it will be fixed in a future SaaS release.
However, I do find it odd that the LTI library would cause such a dramatic end to the connection. The value isn't really used anywhere in the LTI library, right? In other words, wouldn't it be better to drop the check for this particular value. Not the accept_ values because they are there to guarantee that the tool is launched in the way the author has intended it. I am referring to dropping the check for the value in launch_presentation_document_target only. If it is not used anywhere, what would be the point of terminating the LTI launch request right then and there?

**Comment by spvickers** [comment]
The library is designed to act as an interface between the platform and the tool so you are correct that it makes no use of the parameter value, in much the same way as it makes no use of most of the parameter values.  However, the values are made available for the tool to use.  Compliance with the spec indicates, to me, that the platform is legitimate and trustworthy, but I have been planning to add a "non-strict" mode to the library to allow tools to waive less important infractions should they wish.  I'll try to expedite its addition.  I think this should apply to both parameters in this case, I see no reason to be case sensitive in one case and not the other.

**Comment by spvickers** [comment]
IMS has confirmed that these parameter values must be lowercase to conform to the specification, but I have added a more lenient approach to the code which will convert any uppercase characters.  This will be applied by default but can be disabled by passing a value of true into the handleRequest method.
