### ISSUE TITLE
Error in SQL for install

### ISSUE THREAD

**Issue by alexber220** [celtic-project/LTI-PHP#18]
https://github.com/celtic-project/LTI-PHP/wiki/Installation

column user_pk does not exists in lti2_user_result

ALTER TABLE lti2_user_result
    ADD CONSTRAINT lti2_user_result_lti2_user_FK1 FOREIGN KEY (user_pk)
        REFERENCES lti2_user (user_pk);

ALTER TABLE lti2_user_result
    ADD INDEX lti2_user_result_user_pk_IDX (user_pk ASC);

Duplicate key on write or update

ALTER TABLE lti2_share_key
    ADD CONSTRAINT lti2_share_key_lti2_resource_link_FK1 FOREIGN KEY (resource_link_pk)
        REFERENCES lti2_resource_link (resource_link_pk);

**Comment by spvickers** [comment]
Thanks for the info.  The user_pk error was corrected in the SQL file in the repository (sql/lti4-tables-mysql.sql) but not in the documentation.  This has now been fixed.

Please can you elaborate on the "Duplicate key on write or update" issue you reported; this looks correct to me.  Thanks.

**Comment by alexber220** [comment]
Thanks. Check one more time. SQL is correct.
