### ISSUE TITLE
Missing login_hint parameter

### ISSUE THREAD

**Issue by baukezwaan** [celtic-project/LTI-PHP#22]
I'm not sure, but it seems the validation whether a `login_hint` is provided is too strict. For example, for some Moodle logins we receive the next parameters during login:

```
    [iss] => https://moodle.domain.tld
    [target_link_uri] => https://tool.domain.ltd/our_lti_endpoint/
    [login_hint] => 0
    [lti_message_hint] => 1344568
    [client_id] => aje8dLEm1dI2Uj
    [lti_deployment_id] => 14
```

Following the LTI 1.3 spec, this is valid, since there is a login_hint.
https://www.imsglobal.org/spec/lti/v1p3/#additional-login-parameters-0

But the check in the code seems to be too strict, and will result in a failed login attempt:
https://github.com/celtic-project/LTI-PHP/blob/master/src/Tool.php#L450

As `empty()` also classifies a string '0' as empty. Is it possible to use `isset()` here instead?

**Comment by spvickers** [comment]
Thanks for reporting this.  I will commit a change to fix this.
