### ISSUE TITLE
Incomplete Documentation for v4

### ISSUE THREAD

**Issue by Alex--C** [celtic-project/LTI-PHP#28]
[Validating a launch request](https://github.com/celtic-project/LTI-PHP/wiki/Messages#validating-a-launch-request) mentions: _Once a record has been initialised for the platform **(see above)**, the verification of the authenticity of the LTI launch request is handled automatically by the `Tool` class._

"Above" seems to refer to the chapter "Initializing a tool consumer", but that's only available in the [Usage docs for v3](https://github.com/celtic-project/LTI-PHP/wiki/Usage-version-3#initializing-a-tool-consumer) .

**Comment by spvickers** [comment]
Thanks.  It now refers to the "Initialising a platform" section on the Usage page.  I'll update the page to note that this section is no longer on the same page.

**Comment by spvickers** [comment]
Documentation has now been updated.  Thanks.
