### ISSUE TITLE
PHP error in parseClaims() with new version

### ISSUE THREAD

**Issue by icebird93** [celtic-project/LTI-PHP#29]
Hi,

I have just upgraded to the new version (4.7.0) and there seems to be a bug in System.php line 1015:
`unset($payload->{$claim}[$mapping['claim']]);`
whereas line 1018:
`unset($payload->{$claim}->{$mapping['claim']});`

PHP error message: Cannot use object of type stdClass as array

Changing line 1015 to the same resolves the issue.

Thanks,
Aron

**Comment by spvickers** [comment]
Thanks for the report.  I have not been able to replicate this issue.  Are you able to let me know what version of PHP you are using and which platform (or share a sample JWT from the platform)?  Thanks.

**Comment by icebird93** [comment]
I am using the following setup:
- PHP 7.4.28
- Moodle 3.11.6+ (Build: 20220401)
- LTI 1.3
- Firebase JWT library is used

Looking into FirebaseClient, it seems, payload is decoded as stdClass and not as array:
`json_decode(JWT::urlsafeB64Decode($sections[1]))`

And that payload is used in parseClaims in System.php

Here is a partial error stack trace:
#0 /www/vendor/celtic/lti/src/System.php(959): ceLTIc\LTI\Tool->parseClaims()
#1 /www/vendor/celtic/lti/src/Tool.php(422): ceLTIc\LTI\Tool->parseMessage()
#2 /www/vendor/celtic/lti/src/Tool.php(473): ceLTIc\LTI\Tool->getMessageParameters()
#3 [...]: ceLTIc\LTI\Tool->handleRequest()
[...]

I hope these help. Thanks!

**Comment by spvickers** [comment]
Thanks for the info.  I think I have fixed the root cause.

**Comment by spvickers** [comment]
Thanks for reporting this - version 4.7.1 has now been released which I believe resolves it.

**Comment by icebird93** [comment]
Seems to be working with my use case, thank you for the quick fix!
