### ISSUE TITLE
LTI: OAuth 2.0 Error

### ISSUE THREAD

**Issue by VkTestLab** [celtic-project/LTI-PHP#31]
Hello,

I am using Celtic-project / LTI-PHP package for creating Tool Consumer for LTI Lunch URL But I got the below error message when I lunch LTI URL 

Error  : LTI: OAuth 2.0 Error

Please find attached the screen with more details 
![Screenshot_1](https://user-images.githubusercontent.com/103170365/162953012-3f513da2-5666-431e-b52d-ce9825528c76.png)

**Comment by spvickers** [comment]
Not sure you have provided sufficient information to identify the cause of this error.  It appears that you are using the original LTI security model based on OAuth 1.0A, so an error message of "LTI: OAuth 2.0 Error" seems odd.  Is this error being generated by the library?  You can use a site such as https://lti.tools/oauth/ to check the signature being generated for your launch message.  If the signature is correct then the most likely causes are an incorrect timestamp, a re-used nonce value, a discrepancy between the key and secret being used by the platform and the tool.

**Comment by spvickers** [comment]
Closing as no response received.  Please re-open if this is still an issue for you.
