### ISSUE TITLE
Grade Passback

### ISSUE THREAD

**Issue by cyrodjohn** [celtic-project/LTI-PHP#37]
Apologies this is not an issue. Just wanted to ask where is a good place to start with grade passback? 

Thanks

**Comment by spvickers** [comment]
I suggest you take a look at the Outcomes service section of the documentation at https://github.com/celtic-project/LTI-PHP/wiki/Outcomes-service.

**Comment by cyrodjohn** [comment]
Hi thanks. Is this for LTI 1.3?

**Comment by spvickers** [comment]
It supports all versions of LTI, including the LTI 1.3 Score and Result services included in the Assignment and Grades Services specification.

**Comment by cyrodjohn** [comment]
Okay thanks!
