### ISSUE TITLE
Assignment and Grade Services (AGS) OAuth2.0 Access Token Request and Storage

### ISSUE THREAD

**Issue by danhammari** [celtic-project/LTI-PHP#38]
Dear Stephen Vickers,

I am using LTI 1.3/Advantage Assignment and Grade Services (AGS) routines to send grades from my tool to an LMS platform, and am receiving this error message:

    Unable to obtain an access token for scope: https://purl.imsglobal.org/spec/lti-ags/scope/score

I suspect that my issue is that I need to first request an access token with the correct scope and store it in the `lti2_access_token` table. The `AccessToken` class has a `get()` method that handles fetching and storing a token from the platform, and the `Service/Score` class has a constant named `$SCORE` that holds the correct scope I want for the access token.

At first I thought that the problem was that I wasn't properly storing the `$platform->accessTokenUrl` value in the `lti2_consumer` table, but upon reviewing the `DataConnector->fixPlatformSettings()` method I saw that the `lti2_consumer`.`settings` JSON attribute named `_oauth2_access_token_url` should be translated to the `$platform->accessTokenUrl` value:

    $platform->accessTokenUrl = $platform->getSetting('_oauth2_access_token_url', $platform->accessTokenUrl);

The problem seems to be with the `Service` class `send()` method not being able to fetch a version of the access token that has the required scope. We fetch the platform's token, check to see if it has the requested scope, fetch a new token with the requested scope added, check to see if the scope is attached, then try one last time to get a token with just the requested scope. The reason the token never adds the requested scope is because of this line in the `AccessToken` `get()` method:

    if (!empty($url) && !empty(Tool::$defaultTool) && !empty(Tool::$defaultTool->rsaKey)) {

In my case the `Tool::$defaultTool` value is always null. This is probably because I have extended the `Tool` class in my system and have not set its static reference to point to my custom class. I have looked through the code and have not been able to find where the `Tool::$defaultTool` value is assigned a value. Perhaps I need to extend the `AccessToken` class as well and change the `use` section after the namespace to reference my custom class instead:

    use App\LTI\myTool as Tool;

I will give this a try and see if it solves my access token issues. Static references make it difficult to extend a core class, but this may be the best way for me to make the necessary changes for my situation. Please let me know if you are aware of a better way to customize the Tool class without having to worry about static references used elsewhere in the code.

Sincerely,
Dan Hammari

**Comment by danhammari** [comment]
This fix seems to work.
I updated the constructors for my classes that inherit from the `ceLTIc\LTI\Tool` class.

**Comment by spvickers** [comment]
Excellent, thanks for confirming that.  In general the library tries to handle getting and renewing access tokens automatically.
