### ISSUE TITLE
User.php - can the hasRole() function be public?

### ISSUE THREAD

**Issue by chrispittman** [celtic-project/LTI-PHP#39]
`src/User.php` has a few functions (`isAdmin()`, `isStaff()`, `isLearner()`) to determine what class of user this is.  These all use the `hasRole()` function internally.

Several of our LTI tools make more fine-grained distinctions than the User->isThing() functions allow for.  For example, Content Developers can edit content but can't grade student work; Instructors can do both.  Both user types right now are lumped into the `isStaff()` function and can't easily be distinguished by the app.

What do you think about making `hasRole()` public instead of private, so that interested tools could query specific roles without having to duplicate your role-parsing logic in the app itself?

**Comment by spvickers** [comment]
That sounds like a good suggestion, though given the limited number of roles which I suspect are used, would it also solve your needs if isContentDeveloper(), isTeachingAssistant() and isInstructor() methods were added?

**Comment by chrispittman** [comment]
We have a few scattered uses for the Manager and Mentor LTI roles too, but those three would cover 90% of what we need, and we could work around the rest manually.

**Comment by spvickers** [comment]
Thanks, I'll ponder on this a little more.  My initial concern about opening up the hasRole() method is how easy it would be to support across changes to the spec.  We already have three different versions of role names.  But perhaps I am overly concerned about this.

**Comment by chrispittman** [comment]
Fair enough, it's a 100% valid concern.  If I can help with anything here, please let me know!

**Comment by spvickers** [comment]
For now I have added new methods: isInstructor, isContentDeveloper, isTeachingAssistant, isManager, isMember, isOfficer, isMentor and also fixed an issue with the URI for a teaching assistant in LTI 1.3.  I propose to look at adding public methods such as hasContextRole, hasInstitutionRole and hasSystemRole rather than making the hasRole method public.  But hopefully the new methods will be useful in the meantime.
