### ISSUE TITLE
Wrong use statement in UserResult

### ISSUE THREAD

**Issue by scollovati** [celtic-project/LTI-PHP#44]
This `use` statement https://github.com/celtic-project/LTI-PHP/blob/master/src/UserResult.php#L5 should be replaced with `use ceLTIc\LTI\DataConnector\DataConnector;` as in other files, like [ResourceLink](https://github.com/celtic-project/LTI-PHP/blob/master/src/ResourceLink.php#L5).

This minor error causes issue with type validators like PHPStan in projects that use this library.

**Comment by spvickers** [comment]
Thanks for reporting this.
