### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by sandermenke** [celtic-project/LTI-PHP#49]
Is there an ETA on PHP 8 support? We are upgrading our project and another package in our project is requiring an updated version of firebase/php-jwt (^6.3.1). 

Is it possible to allow an upgrade of php-jwt? In the changelog in says it dropped support for PHP <7.0
https://github.com/firebase/php-jwt/blob/main/CHANGELOG.md

**Comment by spvickers** [comment]
I hope to release an update for PHP 8 this month.  But if you are already using PHP 8, have you tried using an updated release of the php-jwt library?  I am not aware of any issues with doing so, but let me know if you encounter any.  Or is there code in this library which PHP 8 complains about?

**Comment by spvickers** [comment]
Check here for the [class library documentation](http://www.spvsoftwareproducts.com/php/lti/docs-v5.0.0-rc1/) for this draft release for PHP 8.1.

**Comment by spvickers** [comment]
Updated the [class library documentation](http://www.spvsoftwareproducts.com/php/lti/docs-v5.0.0-rc2/) for latest changes to draft release for PHP 8.1.

**Comment by spvickers** [comment]
Expecting to release this update for PHP 8.1 by the end of this month unless anyone has any issues to report with it.  See [Updating page](https://github.com/celtic-project/LTI-PHP/wiki/Updating) for details of changes from version 4.

**Comment by arthurnumen** [comment]
Hi @spvickers, Appreciate and thank you for this info, is still on track with the release for PHP 8.1?

**Comment by spvickers** [comment]
Yes, still on track to release this month.

**Comment by spvickers** [comment]
Version 5.0.0 has now been released.
