### ISSUE TITLE
LTI launches can be blocked by popup blockers due to lack of human interaction

### ISSUE THREAD

**Issue by chrispittman** [celtic-project/LTI-PHP#50]
During LTI launch in an iframed tool, we're seeing new users in Chrome being blocked by that browser's popup blocker on their first usage of the tool.  I think the scenario that's happening here is:

1. Chrome isn't allowing a cookie to be set, due to the new-ish restrictions on setting cookies in iframes for untrusted sources (i.e., ones the user hasn't interacted with yet.)
2. Celtic's LTI-PHP library is correctly detecting that this has happened, and is creating a form with a "_blank" target to open the tool in a new window instead.  This form is automatically submitted by Javascript.
3. Chrome's popup blocker detects a request to open a popup window which the user hasn't requested via a UI interaction, and blocks the popup.
4. The user sees a blank page, and a 'popup blocked' notification which is easy to miss.  There's no visible way forward from this point.

The key part here is in step 2; submitting the form happens without user interaction.  And there's no visible controls on the resulting page (https://github.com/celtic-project/LTI-PHP/blob/62ac401509e0122e3af4e768802dc0df15161ef9/src/Util.php#L381-L430
) , giving the user a fallback option if this situation happens.

There are a couple of approaches to dealing with this, but one fairly straightforward-seeming one is to alter `Util->sendForm()` to include a 'Please wait...' message, along with an `<input type='submit'>` which becomes visible after a few seconds.  If the user clicks that, that counts as user interaction, which is enough to cause the popup to be allowed.

Would be happy to discuss and/or collaborate on a pull request for this.

**Comment by spvickers** [comment]
Thanks, I assume you are using this library for developing an LTI platform.

I agree with your suggestion; this is what I have done with my own LTI platform implementations (not using this library).  I will add this feature when a message is being sent from an LTI platform.

**Comment by chrispittman** [comment]
I'm a little fuzzy on the 'Platform' term in LTI, but we're developing tools, not LMSes.

**Comment by spvickers** [comment]
An LTI platform is what used to be referred to as a Tool Consumer and is the system from which a user is launched into an LTI tool (used to be referred to as a Tool Provider).  An LMS is a typical example of an LTI platform (although they can also act as LTI tools).

The LTI launch message is generated by the platform and so, if you are developing LTI tools, the issue you are experiencing needs to be reported to the author(s) of the platform(s) you are using.

**Comment by spvickers** [comment]
On reflection, perhaps I need to explore this a little further, because as you said, the library is forcing the tool into a new window if it encounters a cookie issue, so the absence of a button to submit when blocked is an issue here.  I'll investigate further.

**Comment by chrispittman** [comment]
Thanks.  Above is a link to how the issue presents in one of our LTI tools,
if that helps to explain the problem.

**Comment by spvickers** [comment]
I have committed an initial fix for this issue with a hard-coded delay of 5 seconds.  I will explore making this value a property which can be changed.  Thanks for reporting this and let me know if it does not solve your problem.

**Comment by chrispittman** [comment]
In initial testing, this works, but the user experience is a little fiddly.  The message takes 5 seconds to pop up, and the OIDC launch state times out 10 seconds after the launch.  So the user only has a window between 5 and 10 seconds to use that button, with no visible indicator of when those times are.

An alternate strategy may be to try to open a new window, and see if it fails.  If so, offer the submit button immediately, and start a timer which removes it once the OIDC state expires.  Either way, tell the user that their tool isn't here; it's over in a new window (which also gives them the clue that they can relaunch the tool if they've closed that window).

Some code that tested well for that over here is this patch to Util::sendForm():

```
    public static function sendForm($url, $params, $target = '', $javascript = '')
    {
        // FIXME: I'm assuming this is the OIDC state timeout, based on the comments,
        // but this doesn't appear to be used anywhere in the code just yet.
        $tool_state_life = Tool::$stateLife;

        if (empty($javascript)) {
            $javascript = <<< EOD
function doUnblock() {
  var el = document.getElementById('id_blocked');
  el.style.display = 'block';
}

function doNewWinSuccessMessage() {
   var success_el = document.getElementById('id_newwin_success');
   success_el.style.display = 'block';
   var blocked_el = document.getElementById('id_blocked');
   blocked_el.style.display = 'none';
}

function doOnLoad() {
  if ((document.forms[0].target === '_blank') && (window.top === window.self)) {
    document.forms[0].target = '';
  }
  if (document.forms[0].target === "_blank") {
    // Popup blockers may be blocking the _blank window.  If so, detect that and offer a manual form submit instead.
    var new_window_name = "lti"+Math.random();
    document.forms[0].target = new_window_name;
    var new_window_ref = window.open('', new_window_name);
    var show_successful_launch_msg_timeout_secs = 0;
    if (new_window_ref) {
      // If the new window exists, it's a valid submit target.  Submit the form.
      document.forms[0].submit();
    } else {
       // If the new window doesn't exist, the popup was blocked.  Show an unblock message 
       doUnblock();
       show_successful_launch_msg_timeout_secs = {$tool_state_life};
    }
    setTimeout(doNewWinSuccessMessage, show_successful_launch_msg_timeout_secs * 1000);
  } else {
    document.forms[0].submit();
  }
}

window.onLoad = doOnLoad;
EOD;

.... skip ....

<body>
  <form action="{$url}" method="post" target="{$target}" encType="application/x-www-form-urlencoded">
    <p id="id_blocked" style="display: none; color: red; font-weight: bold;">
      Your browser may be blocking this request; try clicking the button below.<br><br>
      <input type="submit" value="Continue" onClick="doNewWinSuccessMessage()" />
    </p>
    <p id="id_newwin_success" style="display: none;">
      Your tool was loaded in a new window.
    </p>
```

What do you think?  I'd be happy to work up a pull request with this change if you prefer.

**Comment by spvickers** [comment]
Thanks for the feedback.  I have not encountered the same issue with the expiry of the state value in my testing but I'll check this out.  In the meantime I have just committed changes which allow you to specify the delay to be used.  Just add a statement like this to configure a 2 second delay:
`LTI\Tool::$formSubmissionTimeout = 2;
`

**Comment by spvickers** [comment]
Note also that you can change the life of the state value like this:
`LTI\Tool::$stateLife = 60;`

**Comment by chrispittman** [comment]
Thanks!  I'm hoping that the approach I outlined above means you don't need a $formSubmissionTimeout variable at all; you know immediately if the form is necessary or not, and don't have to fiddle with timings.

**Comment by spvickers** [comment]
Your suggestion is good, but since I would not expect this issue to arise in most cases, it seems unfortunate that a test window always has to be opened first before a form can be submitted.  I'll ponder further on this.

**Comment by chrispittman** [comment]
Unless you're seeing something that I'm not, the window that we're opening isn't a test window.  If we open it successfully, we then use it to submit the form to.  This happens because the same name is reused in both contexts:

```
    document.forms[0].target = new_window_name;
    var new_window_ref = window.open('', new_window_name);
```

See this JSFiddle to try it live: https://jsfiddle.net/t27fr8vy/

**Comment by spvickers** [comment]
Sorry, I had not noticed the line which set the target of the form to the new window.

**Comment by spvickers** [comment]
I am proposing to leave the code using a timeout value for now, though I have amended the commit to set the default to 2 seconds and move its setting to the Util class.
