### ISSUE TITLE
how can I extract $http->response after calling the send method ?

### ISSUE THREAD

**Issue by vkdevhero** [celtic-project/LTI-PHP#54]
Hi @spvickers 

I hope you are doing well.

I am using your package to implement a Tool provider. There is an issue with the result section. Using the celtic package, I am throwing the result from the tool provider to the tool consumer. I am throwing the result to the url passed by the tool consumer, but I am getting a below  response After call Curl.

![image](https://user-images.githubusercontent.com/127824936/236409043-6e18ce27-447e-4090-9f80-92fb1c585f67.png)

![image](https://user-images.githubusercontent.com/127824936/236399731-491766ee-df25-43e3-9527-2abb89a7da8d.png)

According to your code, you will extract the response after calling the $http->send() method.

I have print $http before the called the $http->send(). You can see I got null response in $http.

![image](https://user-images.githubusercontent.com/127824936/236412448-3d440ee3-86ea-4753-966a-e93e0bbcda76.png)

![image](https://user-images.githubusercontent.com/127824936/236389900-2f5924ac-65c3-4bbf-9736-2d5b8012f66d.png)

In order for me to determine whether or not the result was successfully sent to tool consumers, how can I extract $http->response after calling the send method?

Thanks

**Comment by spvickers** [comment]
The `response` property will only be set after you have called the `send` method.  After that you can check the `ok` property to see if the request was successful.

**Comment by vkdevhero** [comment]
Hi @spvickers 
I got it, but after calling $http->send(), I only received a true or false result, so I am unable to extract the response.

**Comment by spvickers** [comment]
The `send` method merely returns a boolean, but the `http` object should contain the `response` property.  In case you've not seen it, the documentation of this object can be found at http://www.spvsoftwareproducts.com/php/lti/docs/classceLTIc_1_1LTI_1_1Http_1_1HttpMessage.html

**Comment by vkdevhero** [comment]
@spvickers 
That's fine. The $http object looks like this. Could you please let me know why the response is blank?

![image](https://user-images.githubusercontent.com/127824936/236447775-5c6a9b6c-8fb7-4151-b494-daa136e49ed5.png)

**Comment by spvickers** [comment]
The `ok` property is set to `false` which indicates there was an error, hence the `response` property may not be populated.  Check your log files for any errors.

**Comment by vkdevhero** [comment]
Ok I will check Thanks for your quick reply.

**Comment by vkdevhero** [comment]
Hi @spvickers 

In doLTI11Service function, the value of $ok variable is set by default to false. When I receive a response from the Curl call, you set it to true. So I don't think any errors occurred.


![image](https://user-images.githubusercontent.com/127824936/236456117-1b4f9b81-7e90-4a53-bb37-bc9b697c5aa1.png)

![image](https://user-images.githubusercontent.com/127824936/236456274-d971e44d-5c91-484c-bacd-036a652492d4.png)

**Comment by spvickers** [comment]
Yet, in the image you gave of the `http` object, the property was set to `false`.  Was this image of the object after calling the `send` method?  Does the `send` method return `true`?

**Comment by vkdevhero** [comment]
Yes , Is there a place in the response value that is populated?

**Comment by spvickers** [comment]
The response you posted an image of above had no body - did you remove this?  If a body is being returned by the platform then I cannot explain why it is not being populated in the `http` object.  Why is access to the response body important to you?  You could try using the StreamClient instead of the CurlClient to see if that gives you any different behaviour (see the `HTTP clients` section at https://github.com/celtic-project/LTI-PHP/wiki/Services).

**Comment by vkdevhero** [comment]
Hi @spvickers 

I used Steam Client still facing the same issue.

![image](https://user-images.githubusercontent.com/127824936/236467526-a5305aa2-2330-4ccc-83b6-6bad542e6b9b.png)

**Comment by spvickers** [comment]
That last image looks like it was taken before calling the `send` method.  What makes you so sure that the platform is returning a body in its response?

**Comment by vkdevhero** [comment]
I was taken last image after calling the send method. but the issue is i did not getting the value in response key.

![image](https://user-images.githubusercontent.com/127824936/236469537-80900e0e-bff6-418f-96d9-2e5c17124ec5.png)

**Comment by spvickers** [comment]
The image you gave was not of the `response` property, but of the `http` object.  It showed the `ok` property with a value of `false` which suggested to me it was prior to the calling of the `send` method, hence my question.  Have you tried dumping the response being received by the client implementation just to prove that a body was included?  The original image you posted to this issue showed a response with headers but no body.

**Comment by vkdevhero** [comment]
After calling the send method, I dumped the $http->response, but it was blank.

**Comment by vkdevhero** [comment]
Response received by Client : 

![image](https://user-images.githubusercontent.com/127824936/236475202-417631b4-2207-4815-961a-08f94de7da4d.png)
![image](https://user-images.githubusercontent.com/127824936/236475303-35ba0113-3637-4ec0-bf45-d711fd74fce5.png)

See the below images i got below response after calling $http->send() method.
![image](https://user-images.githubusercontent.com/127824936/236475834-aaf9f67f-6361-45aa-a4e9-4a22b33e953b.png)
![image](https://user-images.githubusercontent.com/127824936/236475932-5379ed36-c955-4c1e-94b9-e102fe47ec0b.png)

**You can see I got the blank value in response key.**

**Comment by spvickers** [comment]
Sorry, I do not see the problem here.  The response you show only includes headers and no body, hence the `response` property is expected to be an empty string.

**Comment by vkdevhero** [comment]
Ok can you send me sample of body  ??

**Comment by spvickers** [comment]
What problem are you having which makes you want to be able to inspect the body of the response?   An example of the body of a response can be found in the 1EdTech specification for this service.

**Comment by vkdevhero** [comment]
Hi @spvickers 
I have one question regarding result. after throwing the result from tool provider to tool consumer, can I get any response in tool provider's side?

**Comment by spvickers** [comment]
Sorry, I do not understand your question.   Please can you explain it further.  Thanks.

**Comment by vkdevhero** [comment]
Hi @spvickers 

We have developed a tool provider for tool implementation. Once the tool consumer completes the course in our platform, we send the result to tool consumer on below url (lis_outcome_service_url). So after sending the result, can I get any response ??

I see your code.  you have write the below code after sending the result to tool consumer.

![image](https://user-images.githubusercontent.com/127824936/236792760-55d43159-fec2-4a40-a33a-a26d27dc322a.png)

So my question is how i get the below response after throwing the result to tool consumer in my response filed.becuase as of now I get empty  string in my response key.

$this->extNodes['imsx_POXHeader']['imsx_POXResponseHeaderInfo']['imsx_statusInfo']['imsx_codeMajor']

**Comment by spvickers** [comment]
In all the examples you showed before in this issue, it looked like your tool consumer was not sending a body with its response.  Are you sure it is doing so?  If not, the empty `response` property would be correct.  If so, are you able to confirm what tool consumer you are using and/or supply a copy of the body it is returning?

**Comment by spvickers** [comment]
What I was asking about was the body sent by the tool consumer when responding to your Basic Outcomes service request.  At present all your examples showed this as being empty and hence the empty `response` property is correct.  Is there a reason why you wish to be able to access the body of the response?  I have not come across any use cases for wanting to do so.

**Comment by vkdevhero** [comment]
No , There is no any reason to access the body of the response. I just want the status of result like true or false but I look in your  code you are fetching the some keys from the response of body that's why I am asking . So is there any reason to fetch the some parameters from the response body ??

**Comment by spvickers** [comment]
If the tool consumer is complying with the LTI specification for this service, then it should be returning the status of the request in the body of its response.  The code extracts this value.  In your case it looks like the tool consumer is not complying with the spec by not doing returning a body.

**Comment by vkdevhero** [comment]
Ok Thanks
