### ISSUE TITLE
Fatal error in ceLTIc\LTI\Tool::ID_SCOPE_RESOURCE

### ISSUE THREAD

**Issue by aweed1** [celtic-project/LTI-PHP#60]
[LTI plugin](https://github.com/celtic-project/LTI-PHP) was updated from the previous version to 5.0.0. After updating, visiting the site yields the below stack trace.

Some info about the environment:

PHP 8.0.29
WordPress 6.0.5
[LTI Tool v3.2.1](https://github.com/celtic-project/wordpress-lti)

Fatal error: Uncaught Error: Undefined constant ceLTIc\LTI\Tool::ID_SCOPE_RESOURCE in /home/someuser/public_html/wp-content/plugins/lti-tool/includes/lib.php:708 Stack trace: 
#0 /home/someuser/public_html/wp-content/plugins/lti-tool/lti-tool.php(119): lti_tool_get_options() 
#1 /home/someuser/public_html/wp-includes/class-wp-hook.php(307): lti_tool_once_wp_loaded('') 
#2 /home/someuser/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /home/someuser/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) 
#4 /home/someuser/public_html/wp-settings.php(620): do_action('wp_loaded') 
#5 /home/someuser/public_html/wp-config.php(117): require_once('/home/someuser/...') 
#6 /home/someuser/public_html/wp-load.php(50): require_once('/home/someuser/...') 
#7 /home/someuser/public_html/wp-admin/admin.php(34): require_once('/home/someuser/...') 
#8 /home/someuser/public_html/wp-admin/index.php(10): require_once('/home/someuser/...') 
#9 {main} thrown in /home/someuser/public_html/wp-content/plugins/lti-tool/includes/lib.php on line 708

I wasn't sure whether to post the issue in this repo, or the [wordpress-lti](https://github.com/celtic-project/wordpress-lti) one as the issue popped up when LTI-PHP was updated to version 5.

**Comment by spvickers** [comment]
Thanks for the report which looks like it relates to the WordPress plugin for this library.  Note that the plugin requires PHP 8.1 and so I am surprised that your WordPress site installed it when you are only using PHP 8.0.  I recommend that you revert to the previous release (4.10.2) or update to PHP 8.1

**Comment by aweed1** [comment]
I believe the issue is that Tool::ID_SCOPE_RESOURCE is defined in the previous version of the plugin (see: https://github.com/celtic-project/LTI-PHP/blob/4c33db8d7d33e11b2239aed9ecb09ea3614e609a/src/Tool.php) but not in the current one.

**Comment by spvickers** [comment]
See my previous response; I think they crossed.

**Comment by aweed1** [comment]
Got it! Upgrading to PHP 8.1 seemed to solve the issue. It might be a good idea to list the PHP version required in the readme. I can see others having the same issue.

Thanks for your support / all the awesome dev work :)
