### ISSUE TITLE
question about logic: can variable both not exist and have a positive string length?

### ISSUE THREAD

**Issue by danhammari** [celtic-project/LTI-PHP#62]
https://github.com/celtic-project/LTI-PHP/blob/cf2212b2659fd7f9cf04685d4d46cb7b65eb578d/src/Tool.php#L1378-L1383

I'm a bit confused by the two `if` statements referenced above.
The logic seems as if it will never be true:

```
if (!isset($var) && strlen(trim($var)) > 0) {
  // do logic
}
```
Should the evaluation instead be an `or` statement with the second comparison being equal to zero?

**Comment by spvickers** [comment]
Thanks for reporting this; you are quite right.  I will commit a correction for this.  Which LTI platform are you using with the LtiSubmissionReviewRequest message?

**Comment by spvickers** [comment]
Closing this issue as no reply received to my question.
