### ISSUE TITLE
Context and Resource Link Tables: how to store additional custom LTI attributes in the settings field?

### ISSUE THREAD

**Issue by danhammari** [celtic-project/LTI-PHP#67]
Hi Stephen,

I am working with the Assignment and Grade Services (AGS) 2.0 specification and building the connection between deep links and the score return service. The `lti2_context` and `lti2_resource_link` tables seem to be designed to help remember which deep links requested which resources so scores can be returned to the associated `custom_lineitem_url` provided with the deep link. I am finding that I need to store additional context information in order for my tool to associate its local `assignment_id` to the platform's `lti_resource_link_id`. 

When my tool sends a deep link reference to a platform I add some custom attributes to the `LtiLinkItem` using its `addCustom()` method. When platform users click on those deep links I receive back these custom attributes in the JWT payload under the `https://purl.imsglobal.org/spec/lti/claim/custom` entity:

```
"https://purl.imsglobal.org/spec/lti/claim/custom":{
    "assignment_id":"24983",
    "unit_id":"434"
}
```

I would like to store these additional custom attributes in my database, perhaps in the `lti2_context`.`settings` field or the `lti2_resource_link`.`settings` field. Unfortunately, those fields currently only store select custom attributes of the `https://purl.imsglobal.org/spec/lti-ags/claim/endpoint` entity. Here is an example from the `lti2_context`.`settings` field:

```
{
"custom_lineitems_url":"https://localhost:3001/lti/v1p3/platform_outcomes"
"custom_ags_scopes":
    "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem,
    https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly,
    https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly,
    https://purl.imsglobal.org/spec/lti-ags/scope/score"
}
```
And here is an example from the `lti2_resource_link`.`settings` field:
```
{
"custom_lineitems_url":"https://localhost:3001/lti/v1p3/platform_outcomes",
"custom_lineitem_url":"https://localhost:3001/lti/v1p3/platform_outcomes/402438163",
"custom_ags_scopes":
    "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem,
    https:\/\/purl.imsglobal.org\/spec\/lti-ags\/scope\/lineitem.readonly,
    https:\/\/purl.imsglobal.org\/spec\/lti-ags\/scope\/result.readonly,
    https:\/\/purl.imsglobal.org\/spec\/lti-ags\/scope\/score"
}
```

My first thought was to see if I could re-use the `settings` fields in the `lti2_context` or `lti2_resource_link` tables. However, this might cause problems if the code assumes that all values stored in these fields should be children of the `https://purl.imsglobal.org/spec/lti-ags/claim/endpoint` entity. Are you aware of any issues that might arise if I should inject my custom attributes into either of these fields?

Alternatively, I could create an additional table to extend the storage from the `lti2_context` or `lti2_resource_link` tables. It would use the same `context_pk` or `resource_link_pk` primary keys. It would also have a `custom` column that will hold the child attributes of the `https://purl.imsglobal.org/spec/lti/claim/custom` entity. I could then join across the primary keys to fetch my custom attributes. This would allow my tool to correctly associate its local `assignment_id` values with their `lti_resource_link_id` counterparts in the platform.

Let me know if this is an issue that you have already solved, or if either of these suggestions is something you could recommend moving forward with.

Sincerely,
Dan Hammari

**Comment by spvickers** [comment]
It looks like the values you are wanting to save are specific to a resource link, so you can use the `ResourceLink->setSetting()` method to do this (and the `getSetting()` method to retrieve them).  I recommend using setting names with a prefix of a double underscore (e.g. `__assignment_id`) to avoid any possible clashes with other settings being saved.

**Comment by danhammari** [comment]
When I use the `handleAuthenticationRequest()` method from the Platform class to generate an OIDC auth response, I am unable to include a custom message claim in the message parameters. The `addSignature()` method seems to only allow a limited set of claim entities and disregards others.

BUILDING THE JWT SIGNATURE:
```
// user params
$this->messageParameters['roles'] = 'student';
$this->messageParameters['user_id'] = 'lmsid_123';
$this->messageParameters['lis_person_sourcedid'] = 'sisid_123';

// resource link params
$this->messageParameters['resource_link_id'] = 'resource_link_id_' . $resource_link_id;
$this->messageParameters['resource_link_description'] = 'resource_link_description_' . $resource_link_id;
$this->messageParameters['resource_link_title'] = 'resource_link_title_' . $resource_link_id;

// AGS score reporting
$this->messageParameters['custom_lineitem_url'] = env('API_URL') . '/lti/v1p3/platform_outcomes' . '/' . $resource_link_id;
$this->messageParameters['custom_lineitems_url'] = env('API_URL') . '/lti/v1p3/platform_outcomes';
$this->messageParameters['custom_ags_scopes'] = implode(',', [
    'https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly',
    'https://purl.imsglobal.org/spec/lti-ags/scope/score',
    'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly',
    'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem'
]);

// Context property attributes
$this->messageParameters['context_id'] = 'context_id_' . $resource_link_id;
$this->messageParameters['context_label'] = 'context_label_' . $resource_link_id;
$this->messageParameters['context_title'] = 'context_title_' . $resource_link_id;
$this->messageParameters['context_type'] = 'http://purl.imsglobal.org/vocab/lis/v2/course#CourseOffering';

// custom property attribute `assignment_id` links the tool's assignment id to the `resource_link_id` from the platform
$this->messageParameters['https://purl.imsglobal.org/spec/lti/claim/custom'] = [
    'assignment_id' => $resource_link_id,
];

// SIGNING MESSAGE
$this->messageParameters = $this->addSignature($parameters['redirect_uri'], $this->messageParameters, 'POST', null, $parameters['nonce']);
$html = Util::sendForm($parameters['redirect_uri'], $this->messageParameters);
echo $html;
exit;
```

SIGNED JWT PAYLOAD (DECRYPTED):
```
{
  "https://purl.imsglobal.org/spec/lti/claim/version": "1.3.0",
  "https://purl.imsglobal.org/spec/lti/claim/message_type": "LtiResourceLinkRequest",
  "https://purl.imsglobal.org/spec/lti/claim/tool": {
    "state": "6QsQLRkp"
  },
  "https://purl.imsglobal.org/spec/lti/claim/roles": [
    "student"
  ],
  "sub": "lmsid_123",
  "https://purl.imsglobal.org/spec/lti/claim/lis": {
    "person_sourcedid": "sisid_123"
  },
  "https://purl.imsglobal.org/spec/lti/claim/resource_link": {
    "id": "resource_link_id_1",
    "description": "resource_link_title_1",
    "title": "resource_link_title_1"
  },
  "https://purl.imsglobal.org/spec/lti-ags/claim/endpoint": {
    "lineitem": "https://localhost:3001/lti/v1p3/platform_outcomes/1",
    "lineitems": "https://localhost:3001/lti/v1p3/platform_outcomes",
    "scope": [
      "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem",
      "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly",
      "https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly",
      "https://purl.imsglobal.org/spec/lti-ags/scope/score"
    ]
  },
  "https://purl.imsglobal.org/spec/lti/claim/context": {
    "id": "context_id_1",
    "label": "context_label_1",
    "title": "context_title_1",
    "type": [
      "http://purl.imsglobal.org/vocab/lis/v2/course#CourseOffering"
    ]
  },
  "iss": "ltiv1p3_unittest",
  "aud": [
    "ltiv1p3_unittest_client_id"
  ],
  "azp": "ltiv1p3_unittest_client_id",
  "https://purl.imsglobal.org/spec/lti/claim/deployment_id": "ltiv1p3_unittest_deployment_id",
  "https://purl.imsglobal.org/spec/lti/claim/target_link_uri": "http://127.0.0.1:8000/lti/v1p3/launch",
  "nonce": "Lc3r0exSs3Rb4je9kwKvbAo2rpednUTk",
  "iat": 1699398031,
  "exp": 1699398091
}
```

The message parameter named `https://purl.imsglobal.org/spec/lti/claim/custom` is dropped from the signed JWT payload. I expect this is because it does not belong to the list of predefined LTI claims that are listed under the constant `JWT_CLAIM_MAPPING` in the `Util.php` file. Is this something that we could add to the `addSignature()` method?

**Comment by spvickers** [comment]
Rather than

```
$this->messageParameters['https://purl.imsglobal.org/spec/lti/claim/custom'] = [
    'assignment_id' => $resource_link_id,
];
```
try

```
$this->messageParameters['custom_assignment_id'] = $resource_link_id;
```

The messageParameters contains the equivalent parameters to the JWT and is easier than trying to create the JWT directly.

**Comment by danhammari** [comment]
Thank you for your suggestions. I have been able to add custom attributes to the signed JWT payload and also store those custom attributes in the `lti2_resource_link`.`settings` column. This helps me to more easily look up which of my tool's assignments belong to a given platform's resource id. This allows me to send each user score to the correct platform grade book entry.
