### ISSUE TITLE
LineItem 'pointsPossible' type annotation doesn't allow floats

### ISSUE THREAD

**Issue by chrispittman** [celtic-project/LTI-PHP#68]
In `src/LineItem.php`, `$pointsPossible` is defined as an int.  The Canvas LMS is providing this as a float, which causes a TypeError.  The LTI 1.3 docs (https://www.imsglobal.org/spec/lti-ags/v2p0#scoremaximum) seem to imply that `scoreMaximum` is a number, but not necessarily an integer.  Should the type annotation here be `int|float` instead of `int`?

**Comment by spvickers** [comment]
Thanks for the message.  The spec is certainly suggests that this is the case, though all the examples given use an integer value for this property.  Does Canvas actually allow the points possible (maximum score) for a gradebook column to be a non-integer value?  If not, then perhaps the code just needs to force the float value provided to be an integer.

**Comment by chrispittman** [comment]
Canvas does allow maximum scores to be non-integers, yes.  '0.5' is an allowable max-score in Canvas.

**Comment by spvickers** [comment]
Thanks for confirming this.  I'll commit a change to allow a float value for this property.

**Comment by chrispittman** [comment]
I can confirm that this fixes the problem in Canvas.  Thanks!
