### ISSUE TITLE
Tool's iconUrl is expecting a relative path, not a URL

### ISSUE THREAD

**Issue by etraininteractive** [celtic-project/LTI-PHP#70]
https://github.com/celtic-project/LTI-PHP/blob/d1616b5650dfdc653894eea20d1c0bb2097f2a42/src/Tool.php#L920

I was trying to work out why the Tool Icon was not displaying in the Platform when I passed it my URL path to an icon. Turns out it expects a relative path, not a URL, and prepends the base URL regardless of what you do.

Unless I'm missing something, I'd like to propose a check to see if there is a full URL before prefixing the baseUrl:

```
if (!empty($iconUrl)) {
    $parsedUrl = parse_url($iconUrl);
    // Check if the scheme is present (e.g., 'http', 'https', etc.)
    if (isset($parsedUrl['scheme'])) {
        // The URL is already a full path
        $toolConfig['logo_uri'] = $iconUrl;
    } else {
        // The URL is a relative path; prepend the base URL
        $toolConfig['logo_uri'] = "{$this->baseUrl}{$iconUrl}";
    }
}
```

This is because we have files on our s3 cdn, and not always stored local to the platform.

**Comment by spvickers** [comment]
That makes sense, thanks for the suggestion, I shall make the change.

**Comment by Anderz000** [comment]
Thanks for the quick action @spvickers!

**Comment by etraininteractive** [comment]
Appreciate the quick action Stephen!

**Comment by spvickers** [comment]
No problem, and thanks for the suggested code which I only just noticed for some reason.  I plan to make a new release before Christmas which will include this change.
