### ISSUE TITLE
getConfiguration() assumes 'messages_supported' contains arrays, breaking older Moodle support

### ISSUE THREAD

**Issue by Anderz000** [celtic-project/LTI-PHP#71]
This might be related to #66, but thought I'd create it separately.

In order versions of Moodle, they do not use the expected array structure in their messages_supported param when registering a tool. Instead of each array element being an array with the key 'type', they list the messages as strings. This was fixed here, but only somewhat recently:

https://github.com/moodle/moodle/commit/b4d9519c473b820aae7c79be517b0cd60843e919

In Tool->getConfiguration(), the $messages are assumed to be arrays, which will cause an error when parsing a relevant request from Moodle versions prior to [v4.0.0-rc1](https://github.com/moodle/moodle/releases/tag/v4.0.0-rc1) 

https://github.com/celtic-project/LTI-PHP/blob/17d380f05655a2fd78fd40e8a6a85b4626d548d0/src/Tool.php#L842-L844

I suggest it look something like this:

```
 foreach ($platformConfig['https://purl.imsglobal.org/spec/lti-platform-configuration']['messages_supported'] as $message) {          
    if (is_array($message) && key_exists('type', $message)){
        $messagesSupported[] = $message['type'];
    } else {
        $messagesSupported[] = $message;
    }
 }
```

**Comment by spvickers** [comment]
As you say this seems to have been a bug in Moodle, but it appears for have been fixed 21 months ago for versions 3.11 and above, which I believe includes all the currently supported releases.  Are you running an older release of Moodle?  If so, are you able to commit the bug fix to your instance instead?

**Comment by etraininteractive** [comment]
Yes, currently overriding it, but can assure you far older Moodles than that are still out there sadly.

**Comment by Anderz000** [comment]
Yes, currently overriding it, but can assure you far older Moodles than that are still out there sadly.

**Comment by spvickers** [comment]
But since these older versions of Moodle are now out of support, surely they are not receiving updates and so committing the bug fix is just a one-off action, and you are no longer impacted by this issue because you have done this.  So, are you reporting this issue because of its potential impact on others?

If anyone else is affected by this issue, please add a comment here so that I can assess its importance.  Thanks.
