### ISSUE TITLE
Fatal Error while handling LTI Request with strict_type enabled.

### ISSUE THREAD

**Issue by CosaroLisa** [celtic-project/LTI-PHP#72]
When first launching an LTI 1.1 App running PHP 8.3 with strinct_types enabled and Celtic v5.0, the method Tool->handleRequest() generates the following fatal error: 
`Uncaught TypeError: unserialized(): Argument #1 ($data) must be of type string, null given in ..`. 
This is due to line 127 of file DataConnector_pdo.php : 
```
 if (!is_array($settings)) {
                $settings = @unserialize($row['settings']);  // check for old serialized setting
            }
```
where the `$row['settings']` retrieved from database is null at first launch, since it is allowed by the DDL of table `lti2_consumer`:
` settings text DEFAULT NULL,`. 
This didn't happen in Celtic versions prior to 5.0. 
It seems the solution could be either to set a default value for the column 'settings' in the `lti2_consumer` table or to correctly manage the  case in which settings are null in line 127.

**Comment by spvickers** [comment]
Thanks for reporting this.  I shall commit a fix for it shortly.

**Comment by CosaroLisa** [comment]
Thank you for the prompt response on the issue. Actually I found something else related to strict_type mode on. 
`Fatal error: Uncaught TypeError: Cannot assign ceLTIc\LTI\Content\TimePeriod to property ceLTIc\LTI\Content\LtiLinkItem::$available of type ?string ` at line 97 of file  `vendor/celtic/lti/src/Content/LtiLinkItem.php`, property $available is inizialized with a TimePeriod type value , but the declaration of the property is of type string.
![image](https://github.com/UNIVERSITABOCCONI/bb-course-survey-lti/assets/113430756/1dc342d3-bb90-4a59-ba41-836a425383b2).
![image](https://github.com/UNIVERSITABOCCONI/bb-course-survey-lti/assets/113430756/d073977a-3b71-4788-b4bd-f426cf7c7ac2)

**Comment by spvickers** [comment]
Thanks for this one too; a fix has been committed.  I am sure there will be others; let me know if you find any of them.

**Comment by CosaroLisa** [comment]
Actually I did find some others: 
1- one is the same as the last one ,  for variable $submission  in file `vendor/celtic/lti/src/Content/LtiLinkItem.php` line 105.
![image](https://github.com/celtic-project/LTI-PHP/assets/113430756/a5e16be3-f8b8-45af-9f97-d6daeeba08e7)
![image](https://github.com/celtic-project/LTI-PHP/assets/113430756/1970f62b-d177-4be1-bcdb-fdd9bfb2f3c7)

2 The other one is about this method `signParameters()` in file `vendor/celtic/lti/src/System.php` line 873. The third parameter $ltiVersionString is of type String but in many places the LTI version is passed as a variable of type enum LtiVersion, so this causes errors at least in two points such as: `Fatal error: Uncaught TypeError: ceLTIc\LTI\Tool::signParameters(): Argument #3 ($ltiVersionString) must be of type string, ceLTIc\LTI\Enum\LtiVersion given, called in /d0/includes/edit-survey.php on line 230 and defined in /d0/vendor/celtic/lti/src/System.php on line 873`
![sign patameters](https://github.com/celtic-project/LTI-PHP/assets/113430756/d0f49695-21db-4719-adfc-b51adf10042f)

A possible solution could be to retrieve the string value from the enum inside the method like this : 
![solution](https://github.com/celtic-project/LTI-PHP/assets/113430756/7d3179ef-d072-47bc-8979-15ca2a7ad5d5)

**Comment by spvickers** [comment]
In this case passing the parameter as a string is deliberate; I think it is the code in edit-survey.php on line 230 which should be updated to pass the value of the enum instead of the enum itself.
