### ISSUE TITLE
isLearner() - isStudent()

### ISSUE THREAD

**Issue by mikesheppard** [celtic-project/LTI-PHP#73]
Good afternoon,

Love the library, well done.  Just a quick suggestion, I'm getting the following as a user:

{"firstname":"Mike","lastname":"Sheppard","fullname":"Mike Sheppard","sourcedId":null,"username":null,"email":"mike@example.com","image":"","roles":["urn:lti:role:ims\\/lis\\/Student"],"groups":[],"ltiUserId":"14592199","ltiResultSourcedId":null,"created":null,"updated":null}

And I'm not being picked up as a Learner or student due to urn:lti:role:ims/lis/Student

Could we add an isStudent function or get public access to the hasRole function so we can work with the above URN ?

**Comment by scollovati** [comment]
`urn:lti:role:ims/lis/Student' is not an LTI1.1 Role https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-32
