### ISSUE TITLE
D2L Brightspace Deep Linking -  Deep linking data claim does not match

### ISSUE THREAD

**Issue by mtravis-interpretive** [celtic-project/LTI-PHP#75]
We are using the latest version of your library and have deep linking working for our Tool in Moodle, Blackboard, and Canvas.  When trying to deep link in D2L, we receive the following message when we finalize our selections and return the response to the LMS Platform.

> Invalid deep linking response from the tool: Deep linking data claim does not match. Please contact your Brightspace Administrator.

I decoded the LtiDeepLinkingRequest from D2L Brightspace, and I saw they are passing a data field that looks like a random encrypted value.  Here is part of the response for reference:

> "https://purl.imsglobal.org/spec/lti-dl/claim/deep_linking_settings": {
>     "accept_types": [
>       "link",
>       "file",
>       "ltiResourceLink",
>       "image"
>     ],
>     "accept_media_types": "*/*",
>     "accept_presentation_document_targets": [
>       "iframe",
>       "window"
>     ],
>     "accept_multiple": true,
>     "auto_create": false,
>     "deep_link_return_url": "redacted",
>     **"data": "14hj6WXYhYqDfTzdN4YPtejaFTqW3fDzuR7d0nHzzFo~"**
>   },

Looking at the spec page ([https://www.imsglobal.org/spec/lti-dl/v2p0](https://www.imsglobal.org/spec/lti-dl/v2p0)), it says that if the data field is passed by the Platform, it must be returned by the Tool as part of the LtiDeepLinkingResponse.

> data **An opaque value which must be returned by the tool in its response if it was passed in on the request.** optional

> The https://purl.imsglobal.org/spec/lti-dl/claim/data value must match the value of the data property of the https://purl.imsglobal.org/spec/lti-dl/claim/deep_linking_settings claim from the LtiDeepLinkinkingRequest message. This claim is required if present in LtiDeepLinkingRequest message.

When I decode the JWT response from our Tool to the Platform, it does not contain the data field.

> {
>   "https://purl.imsglobal.org/spec/lti-dl/claim/content_items": [
>     {
>       "type": "ltiResourceLink",
>       "title": "redacted",
>       "window": {
>         "targetName": "redacted"
>       },
>       "custom": {
>         "coursecode": "redacted",
>         "isi_target": "redacted"
>       }
>     }
>   ],
>   "https://purl.imsglobal.org/spec/lti/claim/version": "1.3.0",
>   "https://purl.imsglobal.org/spec/lti/claim/message_type": "LtiDeepLinkingResponse",
>   "iss": "redacted",
>   "aud": [
>     "redacted"
>   ],
>   "azp": "redacted",
>   "https://purl.imsglobal.org/spec/lti/claim/deployment_id": "redacted",
>   "nonce": "ymK4buJabshFc9Kihirv5ixfj0dismtS",
>   "iat": 1704983114,
>   "exp": 1704983174
> }

Is this something we need to set as part of the response or is it something the library should do automatically if it exists?  If we need to do it, how do we do it?

Also, two unrelated issues.  We recently upgraded to PHP 8.2 and saw a couple messages in our logs while testing compatibility.

- Undefined variable $ext in celtic/lti/src/System.php on line 1513
- Creation of dynamic property ceLTIc\\LTI\\Http\\HttpMessage::$responseJson is deprecated in celtic/lti/src/AccessToken.php on line 183

**Comment by spvickers** [comment]
The data parameter passed in a deep linking request message must be included by the code used to generate a response by a tool. You can see an example of how this can be done in the sample Rating app (https://github.com/celtic-project/Rating-PHP).

Thanks for passing on the PHP 8.2 messages; I'll check these out.

**Comment by mtravis-interpretive** [comment]
I found where you store and pass on the data parameter in the Rating project.  Thanks for the reference.  I'm not sure how I missed that the first time.
