### ISSUE TITLE
Private key(s) store location

### ISSUE THREAD

**Issue by nugen** [celtic-project/LTI-PHP#8]
Hello, Stephen,

I don't have any issue, but I have a question about using the library (Thanks for this very useful one !).
It seems to me that the idea is to have one set of private and public key per consumer to sign requests sent to the platform consumer. If that's right, what's the best solution to store the private keys of each consumer (the public one being in the public_key field of the consumers table) ? 

And can you confirm that when the tool only offers the basiclti launch feature we don't need to configure any key for the consumers.
Thank you in advance.

**Comment by spvickers** [comment]
You can certainly choose to use a separate private key for each platform, but I do not believe this is a requirement of the IMS spec.  The decision as to whether, or not, to do so is a security one and best raised in a forum where you can get advice from a security expert - perhaps try the IMS forum.  I have always used a single private key for a tool but this library should be agnostic about this choice.  It does not prescribe how or where private keys are stored.  The sample Rating app uses a simple approach of placing it in the config.php file, but it could equally be retrieved from a database table or file from outside the web space.

The LTI 1.3-related properties of a platform can be ignored when only using the earlier releases of LTI; see "LTI 1.0/1.1/1.2/2.0" under "Initializing a platform" in the "Usage" section of the documentation.

**Comment by nugen** [comment]
Thank you very much for your advice, I will take a closer look at these aspects of the key security discussions.
For my second question, I was asking this because we can, by configuring our tool on moodle in LTI 1.3 mode, not use a private key (and not provide Moodle with a public key) in case we perform a login/launch. This works fine, only the platform public key (or platform keyset url) is needed for this exchange. We just wanted to confirm that this was normal as we do not use the deeplink or services.

**Comment by spvickers** [comment]
Yes, a private key is only required by a tool for when it sends signed messages/service requests to a platform.  If you are not using any LTI services or the deep linking message, then this will not be the case and so a private key will never be used.
