### ISSUE TITLE
str_replace(): Argument #3 ($subject) must be of type array|string, bool given

### ISSUE THREAD

**Issue by ernst77** [celtic-project/LTI-PHP#81]
My sentry is giving a lot of these errors...
`str_replace(): Argument #3 ($subject) must be of type array|string, bool given`

I guess its comming from here:

        $chResp = curl_exec($ch);
        $message->requestHeaders = explode("\n", trim(str_replace("\r\n", "\n", curl_getinfo($ch, CURLINFO_HEADER_OUT))));
        $chResp = str_replace("\r\n", "\n", $chResp);
        
src/Http/CurlClient.php

[On line 60](https://github.com/celtic-project/LTI-PHP/blob/master/src/Http/CurlClient.php#L60)

Could we handle false (bool) values? Return error instead?

**Comment by spvickers** [comment]
Thanks; I have some code to commit for this issue.  Will do so shortly.
