### ISSUE TITLE
Deprecated: Function utf8_decode()

### ISSUE THREAD

**Issue by scollovati** [celtic-project/LTI-PHP#83]
Deprecated from PHP8.2: https://github.com/celtic-project/LTI-PHP/blob/02e162c538ecf0dee124908e06cd10465ecad166/src/Http/HttpMessage.php#L289

Can be substituted with `mb_convert_encoding($match[2], 'ISO-8859-1', 'UTF-8')`. However, not clear why `$match[2]` needs to be converted to ISO-8859-1.

**Comment by spvickers** [comment]
Thanks for the warning; I'll make the change.  I believe the conversion is because I found examples of these URLs being enclosed in curly double quotes by some platforms.
