### ISSUE TITLE
Wrong type for preg_match in CanvasApi

### ISSUE THREAD

**Issue by sparkp-m** [celtic-project/LTI-PHP#90]
$http->responseHeaders is used as the subject many times in the CanvasApi class and it is declared as an array in the HttpMessage class.

It is imploded with "\n" in other classes when needed as a string - so assume that is the fix in this class. Eg:

LINE 128                if (preg_match('/\<([^\>]+)\>; *rel=\"next\"/', implode("\n", $http->responseHeaders), $matches)) {

**Comment by spvickers** [comment]
Thanks for reporting this.  Should now be fixed.
